theme: jekyll-theme-minimal

title: Jonathan Polk
email: jonathan.polk@svet.lu.se
description: >-
  Political scientist and researcher. This is my academic website.
baseurl: "" # leave this empty for jonathanpolk.github.io
url: "https://jonathanpolk.github.io"
theme: jekyll-theme-minimal
